### ISSUE TITLE
Meetups!

### ISSUE THREAD

**Issue by marcoroth** [ruby-conferences/ruby-conferences.github.io#598]
More and more meetups are coming back, let's add a new section to the website where we can also track meetups

**Comment by adarsh** [comment]
Yes, I agree! We at Ruby Central are trying to support the meetup organizers in a number of ways but helping this effort would be great!

What would the requirements be? Brainstorming:
- Geography-based list of active meetups
  - Filterable by where you live (most people will look for meetup groups where they live, I would think)
  - Some kind of indication of how active they are (meetup within last 3 months? organizer is responsive?

- Event-based calendar
  - Should show 1 upcoming event by default
  - Past events? Is this useful?
  - Importing of external calendar events, especially meetup.com ([API docs here](https://www.meetup.com/api/schema/#event))
  - Other future events?

**Comment by Morozzzko** [comment]
As a guy who relies on the website a lot (thank you for taking over the maintenance by the way), I would like to see it being helpful. So I'm gonna add a few considerations for the feature. Loved it when I read about it, but then I felt like it was just OHMYGOD

More often than not, conferences are larger events targeted towards a wider community. I'd be bold and say that most of conferences on the list are international. So it makes quite a lot of sense to have a centralized place to collect all of those, as people might want to travel to the event.

Meetups, on the contrary, are local. Quite often it's a group of folks who gather around to hang out, talk, discuss things, etc. Those groups are tighter, people know each other better, sometimes they have a chat or forum of some sorts, etc. Arguably, members of a small community aren't going to use rubyconferences.org to learn about _their_ community's upcoming events. Some folks will use it, but I don't think it'd be enough to justify the feature.

Thus, I'm not sure what the primary use-case for the meetup list would be.
Is it "I'm travelling to another country and I'd like to see if there's a Ruby community there"? Or is it "I'd like to have an excuse to travel, let's see if there are any events planned"? 

I think one of the most reasonable use-cases would be "I'm moving to another country, I wonder if there are any meetups there" – but that's an odd topic because of two reasons:

1. Local groups might be in a local language. If the person doesn't speak it, tough luck
2. If the person changes jobs, the good way to find local groups is through colleagues

Meanwhile, the complexity is crazy indeed. Communities may become less active over time, or just stop their activity altogether. If we have too many inactive communities, the list kinda loses its purpose. Yet, the "activity measurement" is incredibly complicated thing. We'll need to:

* See if they have a chat
* Track activity in their chat (how?)
* Track their events
* See if they have a blog/whatever
* Track their Twitter/Mastodon/Whateverelse feeds if they're hanging out like that
* Track their Kommunity or Meetup feed and filter out events which didn't really happen

That's an incredible complexity to have here. So, perhaps it'll be important to figure out the benefits – what are the use cases which will become easier/possible if we add meetups to the platform?

**Comment by marcoroth** [comment]
I was more thinking of adding a list of actual meetup events to the website, not necessarily the "Ruby Meetup Group" themselves. That way we don't have to worry about the activeness of the group or frequency of the events. If they decide to host an event, we add it, otherwise we don't.

But there are also a few "online-only" events that would be helpful to add to the list, like [Philly.rb](https://www.meetup.com/phillyrb/) or [NYC.rb](https://www.meetup.com/nyc-rb/).

For example for the Ruby meetup that just happened in San Francisco it would be something like:

```yml
- name: SF Bay Area Ruby Meetup March 2024
  location: GitHub HQ @ San Franciso
  start_time: 2024-03-05 17:00 PDT
  end_time: 2024-03-05 21:00 PDT
  url: https://lu.ma/r6d0lghm
```

The use-cases (like @Morozzzko pointed out) for me personally are:
* "I'm traveling to another country and I'd like to see if there's a Ruby ~~community there~~ event happening while I'm there" 
* "I'd like to have an excuse to travel, let's see if there are any events planned" 

But happy to hear your thoughts/feedback to this approach.

**Comment by marcoroth** [comment]
I opened https://github.com/ruby-conferences/ruby-conferences.github.io/pull/602 as a first iteration
